### ISSUE TITLE
Only one reg key for the CD version?

### ISSUE THREAD

**Issue by NekoJonez** [thekovic/Indy3DModInstaller#1]
https://github.com/thekovic/Indy3DModInstaller/blob/b594de5d98fcc1de08c45889d481abc19c766dd5/Indy3DModInstaller/Program.cs#L149

I'm currently writing the reg editing part of my powershell version and I noticed that in the tutorial there are two reg keys for the CD version... Don't know when it's the first and when it's the other one. The tutorial says: "Copy the game files from CD". Then it can be this: 
```HKEY_CURRENT_USER\SOFTWARE\Classes\VirtualStore\MACHINE\SOFTWARE\WOW6432Node\LucasArts Entertainment Company LLC\Indiana Jones and the Infernal Machine\v1.0```

I think it would be a safe bet to check if the reg key exists and make it if needed? 
#ThinkingOutLoud

**Comment by thekovic** [comment]
I believe those reg keys are made by "fake" installers that people use to install the game from CD files because the original installer is a 16-bit app and doesn't run on 64-bit Windows. Since they're unofficial tools and the reg values could (in theory) be anything, I chose to not support them initially. I could add them, idk, I'll think about it.

Another interesting option to support would be people running Infernal Machine via DREAMM emulator. I'd have to install it and see how it handles the registry (since it virtualizes the entire OS stack per game install).

**Comment by NekoJonez** [comment]
That's fair. In my Powershell script I wrote a check that it just checks if it exists in the tree before checking the DWORD value. But, I'm not really looking further on why there are two options. It seems like I might have more to look into.

**Comment by thekovic** [comment]
I labelled this as `wontfix` now because I was able to verify on my Windows 98 machine that the official installer produces the registry values that are already supported.
